### ISSUE TITLE
Unable to compile openfst

### ISSUE THREAD

**Issue by fritz-fritz** [jasperproject/jasper-client#34]
openfst will not compile on Ubuntu 13.10 64-bit. (www.openfst.org site is currently down though openfst-1.3.3 and openfst-1.3.4 can be found on mirrors). Have tried numerous recommendations from the cached form of <a href="www.openfst.org/twiki/bin/view/Forum/FstForum&hl=en&gl=us&strip=1">this page</a> with both 1.3.3 and 1.3.4 though can't seem to get openfst to compile:

```
Making install in bin
make[2]: Entering directory `/home/roland/openfst-1.3.4/src/bin'
g++ -DHAVE_CONFIG_H   -I./../include -I./../script    -g -O2 -MT fstarcsort.o -MD -MP -MF .deps/fstarcsort.Tpo -c -o fstarcsort.o fstarcsort.cc
mv -f .deps/fstarcsort.Tpo .deps/fstarcsort.Po
/bin/bash ../../libtool --tag=CXX   --mode=link g++  -g -O2   -o fstarcsort fstarcsort.o ../script/libfstscript.la ../lib/libfst.la -lm -ldl 
libtool: link: g++ -g -O2 -o .libs/fstarcsort fstarcsort.o  ../script/.libs/libfstscript.so ../lib/.libs/libfst.so -lm -ldl
../script/.libs/libfstscript.so: undefined reference to `dlopen'
../script/.libs/libfstscript.so: undefined reference to `dlerror'
collect2: error: ld returned 1 exit status
make[2]: *** [fstarcsort] Error 1
make[2]: Leaving directory `/home/roland/openfst-1.3.4/src/bin'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/home/roland/openfst-1.3.4/src'
make: *** [install-recursive] Error 1
```

with some modifications the build got farther to src/extensions/far before it failed.

I know this isn't an issue with the Jasper Client though this is a dependency and thought you should be aware / maybe had a solution.
